steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/vaulted-program-411701/cloudrun:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/vaulted-program-411701/cloudrun:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cloud-run-app', '--region=us-central1', '--platform=managed', '--image=gcr.io/vaulted-program-411701/cloudrun:$SHORT_SHA']
